---
# Common vars
availability_zone: # add your availability zone

# Volumes
volumes:
  - vol_name: volume1
    vol_size: 50
  - vol_name: volume2
    vol_size: 80

# Security group
security_groups:
  - name: ssh_v3
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_v3
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0


# Instance
instances:
  - instance_name: instance1
    instance_image: # Your preferred image here
    instance_key_name: # Your key pair
    instance_flavor: # Your flavor
  - instance_name: instance2
    instance_image: # Your preferred image here
    instance_key_name: # Your key pair
    instance_flavor: # Your flavor

# Attachments:
attachments:
  - server_name: instance1
    volume_name: volume1
  - server_name: instance2
    volume_name: volume2
