---
# Install dependencies on host
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python3-pip

- name: Install vim
  become: yes
  apt:
    name: ['vim']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get install vim

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk

- name: Install curl
  become: yes
  apt:
    name: ['curl']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
